
package com.ericsson.schemas.vas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookServicePortType", targetNamespace = "http://schemas.ericsson.com/vas/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServicePortType {


    /**
     * 
     * @param saveBookRequest
     * @return
     *     returns com.ericsson.schemas.vas.SaveBookResponse
     */
    @WebMethod
    @WebResult(name = "SaveBookResponse", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "SaveBookResponse")
    public SaveBookResponse saveBook(
        @WebParam(name = "SaveBookRequest", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "SaveBookRequest")
        SaveBookRequest saveBookRequest);

    /**
     * 
     * @param getBookRequest
     * @return
     *     returns com.ericsson.schemas.vas.GetBookResponse
     */
    @WebMethod
    @WebResult(name = "GetBookResponse", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "GetBookResponse")
    public GetBookResponse getBook(
        @WebParam(name = "GetBookRequest", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "GetBookRequest")
        GetBookRequest getBookRequest);

    /**
     * 
     * @param updateBookRequest
     * @return
     *     returns com.ericsson.schemas.vas.UpdateBookResponse
     */
    @WebMethod
    @WebResult(name = "UpdateBookResponse", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "UpdateBookResponse")
    public UpdateBookResponse updateBook(
        @WebParam(name = "UpdateBookRequest", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "UpdateBookRequest")
        UpdateBookRequest updateBookRequest);

    /**
     * 
     * @param deleteBookRequest
     * @return
     *     returns com.ericsson.schemas.vas.DeleteBookResponse
     */
    @WebMethod
    @WebResult(name = "DeleteBookResponse", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "DeleteBookResponse")
    public DeleteBookResponse deleteBook(
        @WebParam(name = "DeleteBookRequest", targetNamespace = "http://schemas.ericsson.com/vas/", partName = "DeleteBookRequest")
        DeleteBookRequest deleteBookRequest);

}
